### ISSUE TITLE
Fork to R package?

### ISSUE THREAD

**Issue by bomeara** [GPlates/gplates_web_service_doc#3]
We'd be interested in wrapping your example functions into an R package to make them easier to use for other software we're developing (while noting that the API may change). It'd probably be fast to do (like an hour to do)-- would  you be ok with us doing this? It'd be appropriate to make you an author given that you've done all the work if you want, but even if you don't want that, we don't want to barge ahead and do this without asking you.

Thanks!

[we = me, @jwiggi18, @LunaSare]

**Comment by michaelchin** [comment]
Yes, sure. You can do that. And we will appreciate it if you could acknowledge EarthByte group https://www.earthbyte.org/ in your package.

**Comment by bomeara** [comment]
Great, will do!
