### ISSUE TITLE
not returning null points

### ISSUE THREAD

**Issue by nussaibahrs** [GPlates/gplates_web_service_doc#4]
Hi!

First of all, thanks for this great tool. It's made life so much easier. 

I'm having some issues with the reconstruction of some points. 

e.g. https://gws.gplates.org/reconstruct/reconstruct_points/?points=-25.1,36.966667,167.899994,-21.4,-1,52.666668,-76.835281,34.980831,-81.571671,9.101111&time=30&model=PALEOMAP&return_null_points 

The reconstructed points are reshuffled with the first points (-25.1,36.966667) ending up at the end of the list. 

`{"type":"MultiPoint","coordinates":[[166.32,-34.44],[-4.55,52.00],[-70.44,34.73],[-79.23, 7.50],[-25.10,36.97]]}`

I'm assuming these are null points and thus not reconstructed (I could be wrong). This so far only happens when using the PALEOMAP model, but works fine with SETON2012. 

Any help is much appreciated!

**Comment by michaelchin** [comment]
Hi Nussaibah,

Thanks for letting us know the problem.

An error in PALEOMAP model has triggered a bug in the web service bug. I have updated the model and code. Can you try it and see if the problem is gone? Thanks.

**Comment by nussaibahrs** [comment]
it works now, thanks!
