### ISSUE TITLE
static polygon reconstruction not working for PALEOMAP

### ISSUE THREAD

**Issue by nussaibahrs** [GPlates/gplates_web_service_doc#5]
Hi! (It's me again, sorry)

Looks like there's an issue with the static polygon reconstruction for the PALEOMAP model:

`https://gws.gplates.org/reconstruct/static_polygons?time=300&model=PALEOMAP` gives the following error

> Server Error (500)

This works fine:
`https://gws.gplates.org/reconstruct/static_polygons?time=300&model=SETON2012`

Thanks for your help!

**Comment by michaelchin** [comment]
Thanks for reporting this bug. We appreciate it. 
A few days ago I updated the PALEOMAP mode. However, two polylines were mixed into the static polygons, which caused this problem. I have fixed the problem . Please try again. thanks.

**Comment by nussaibahrs** [comment]
Thanks for the help!
